# Generated by Django 3.1.7 on 2021-04-29 23:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fonda', '0003_auto_20210429_2312'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='restaurant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='fonda.restaurant'),
        ),
    ]
