# Generated by Django 3.1.7 on 2021-04-22 05:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('groupMenu', models.BooleanField(default=True)),
                ('price', models.FloatField(max_length=10)),
                ('image', models.ImageField(upload_to='menu_images')),
            ],
        ),
        migrations.CreateModel(
            name='MenuPlate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('recibido', 'Recibido'), ('preparando', 'En Preparacion'), ('enviando', 'En Camino'), ('entregado', 'Entregado')], default='recibido', max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Plate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('primer_tiempo', 'Primer Tiempo '), ('segundo_tiempo', 'Segundo Tiempo'), ('tercer_tiempo', 'Tercer Tiempo'), ('cuarto_tiempo', 'Cuarto Tiempo'), ('bebidas', 'Bebidas'), ('Complementos', 'Complementos'), ('ingredientes_extras', 'Ingredientes Extras'), ('tacos', 'Tacos'), ('snack', 'Snack')], default='primer tiempo', max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('price', models.FloatField(max_length=10)),
                ('image', models.ImageField(upload_to='plate_images')),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='RestaurantAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('street', models.CharField(max_length=75)),
                ('suburb', models.CharField(max_length=100)),
                ('municipality', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('int_number', models.CharField(max_length=10)),
                ('ext_number', models.CharField(max_length=10)),
                ('zip_code', models.CharField(max_length=10)),
                ('restaurant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='fonda.restaurant')),
            ],
        ),
    ]
