# Generated by Django 3.1.7 on 2021-04-21 02:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fonda', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='user.client'),
        ),
        migrations.AddField(
            model_name='order',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='fonda.restaurant'),
        ),
        migrations.AddField(
            model_name='menuplate',
            name='menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plates', to='fonda.menu'),
        ),
        migrations.AddField(
            model_name='menuplate',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plates', to='fonda.order'),
        ),
        migrations.AddField(
            model_name='menuplate',
            name='plate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plates', to='fonda.plate'),
        ),
        migrations.AddField(
            model_name='menu',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='menus', to='fonda.restaurant'),
        ),
    ]
