# Generated by Django 3.1.7 on 2021-05-04 04:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fonda', '0005_menu_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='order',
        ),
        migrations.AddField(
            model_name='order',
            name='menu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='fonda.menu'),
        ),
    ]
