# Generated by Django 3.1.7 on 2021-05-04 05:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fonda', '0006_auto_20210504_0445'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuplate',
            name='order',
        ),
        migrations.RemoveField(
            model_name='order',
            name='menu',
        ),
        migrations.CreateModel(
            name='OrderMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ordermenus', to='fonda.menu')),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ordermenus', to='fonda.order')),
            ],
        ),
    ]
