# Generated by Django 3.1.7 on 2021-05-04 23:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fonda', '0008_auto_20210504_2250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plate',
            name='order',
        ),
        migrations.AddField(
            model_name='menuplate',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plates', to='fonda.order'),
        ),
    ]
